### ISSUE TITLE
Purpose of endDate field

### ISSUE THREAD

**Issue by staffanmowitz** [thebiggianthead/sanity-plugin-recurring-dates#18]
What is the purpose of the `endDate` field?

When using a custom rule and specifying an end date, it is included in the _rrule_ using the `UNTIL` parameter. However, it appears that this is not happening when the `endDate` field is used.

In my view, when a custom rule is employed, the `endDate` should be disregarded and replaced by the rule's set options. However, if no custom rule is used, the value from the `endDate` field should be utilized as the `UNTIL` parameter for the _rrule_.

This approach would also prevent conflicts between the custom rule options and the `endDate`. For instance:

-  The `endDate` occurring before the end date set in the custom rule.
-  Occurrences happening after the `endDate` when using the "After X occurrences" option.
-  The `endDate` having a value while the custom rule is configured to never end.

**Comment by thebiggianthead** [comment]
The `endDate` is intended as the end of the event in question and doesn't concern the `UNTIL` of the `rrule`.

For example, an event might start on 2023-01-10 at 13:00 and finish an hour later at 14:00. The end date would determine that this event lasts for an hour, and doesn't impact the generated `rrule`. You could use this end date on your front-end to display an event as necessary.

If an `endDate` is not required, it can be disabled in the plugin config with `hideEndDate: true`.

Forgive me if I've misinterpreted the question here - if there is a bug in how this is working please feel free to reopen this with details.

**Comment by staffanmowitz** [comment]
First, thank you for your prompt response.

I apologize for the misunderstanding regarding the purpose of the `endDate` field. Thank you for providing clarification!

To summarize, does this mean that the only way to specify an end date for a period is by utilizing a custom rule?

**Comment by thebiggianthead** [comment]
Yes - you'd need to use a custom rule to define that. Without that, the Rrule would assume it's an indefinite recurrence.
